name: brawigo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.16.0
  flutter_dotenv: ^6.0.1
  flutter_bloc: ^9.1.1
  image_picker: ^1.2.3
  flutter_native_splash: ^2.4.7
  pinput: ^6.0.2
  image_cropper: ^12.2.1
  equatable: ^2.1.0
  go_router: ^17.3.0
  google_fonts: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  icons_launcher: ^3.0.0
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/images/navbar/
    - assets/icons/

icons_launcher:
  image_path: "assets/icons/icon_launcher.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/logo_brawigo_text_native.png"
  android: true
  ios: true
  android_12:
    image: "assets/images/logo_brawigo_text_native.png"
    icon_background_color: "#FFFFFF"