name: brawigo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.16.0
  flutter_dotenv: ^6.0.1
  flutter_bloc: ^9.1.1
  image_picker: ^1.2.3
  flutter_native_splash: ^2.4.7
  pinput: ^6.0.2
  image_cropper: ^12.2.1
  equatable: ^2.1.0
  go_router: ^17.3.0
  google_fonts: ^8.2.0
  shared_preferences: ^2.5.5
  intl: ^0.20.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  icons_launcher: ^3.0.0
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/images/navbar/
<<<<<<< HEAD
    - assets/font/
  #   - images/a_dot_ham.jpeg
=======
    - assets/icons/
>>>>>>> feat/chat

icons_launcher:
  image_path: "assets/icons/icon_launcher.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

<<<<<<< HEAD
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # Custom fonts configuration
  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/font/PlusJakartaSans-ExtraLight.ttf
          weight: 200
        - asset: assets/font/PlusJakartaSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/font/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/font/PlusJakartaSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/font/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/font/PlusJakartaSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/font/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/font/PlusJakartaSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/font/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/font/PlusJakartaSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/font/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/font/PlusJakartaSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/font/PlusJakartaSans-ExtraBold.ttf
          weight: 800
        - asset: assets/font/PlusJakartaSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
=======
flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/logo_brawigo_text_native.png"
  android: true
  ios: true
  android_12:
    image: "assets/images/logo_brawigo_text_native.png"
    icon_background_color: "#FFFFFF"
>>>>>>> feat/chat
